-- ============================================================================
-- ADD prior_visit_summary COLUMN + RPC EXTENSION
-- ============================================================================
-- Stores the lean PriorVisitSummary JSON (visit_date, prior_icd_primary,
-- prior_plan_summary, key_labs_delta, what_changed) generated by the agent's
-- /clinical/summarise-prior endpoint at consultation save-time.
--
-- On the NEXT consultation for the same patient, the UI reads the most-recent
-- non-null prior_visit_summary and injects it into PatientCase.prior_visit
-- before calling /clinical/plan/stream — so Stage 4/5 prompts and the UI
-- patient card both see what was done last visit.
--
-- Run in Supabase SQL Editor.
-- ============================================================================

-- STEP 1: column
ALTER TABLE consultations
  ADD COLUMN IF NOT EXISTS prior_visit_summary JSONB;

-- Optional: speed up "latest non-null summary for this patient" lookups.
CREATE INDEX IF NOT EXISTS idx_consultations_prior_visit_summary_present
  ON consultations(patient_nric, consultation_time DESC)
  WHERE prior_visit_summary IS NOT NULL;

-- ============================================================================
-- STEP 2: extend save_consultation_bypass to accept + persist the summary.
-- The summary is generated AFTER the consultation row is created (separate
-- agent call), so a thin updater RPC is the cleanest fit. We keep the existing
-- save_consultation_bypass signature unchanged to avoid breaking callers; this
-- new RPC is invoked from supabase.js *after* /clinical/summarise-prior returns.
-- ============================================================================
DROP FUNCTION IF EXISTS update_prior_visit_summary_bypass(TEXT, INTEGER, JSONB);

CREATE OR REPLACE FUNCTION update_prior_visit_summary_bypass(
    p_patient_nric TEXT,
    p_consultation_number INTEGER,
    p_prior_visit_summary JSONB
)
RETURNS JSON AS $$
DECLARE
    result JSON;
BEGIN
    IF NOT is_valid_nric(p_patient_nric) THEN
        RAISE EXCEPTION 'Invalid NRIC format';
    END IF;

    UPDATE consultations
    SET prior_visit_summary = p_prior_visit_summary,
        updated_at = NOW()
    WHERE patient_nric = p_patient_nric
      AND consultation_number = p_consultation_number;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Consultation not found for NRIC % number %',
            p_patient_nric, p_consultation_number;
    END IF;

    SELECT json_build_object(
        'success', true,
        'patient_nric', p_patient_nric,
        'consultation_number', p_consultation_number,
        'prior_visit_summary', p_prior_visit_summary
    ) INTO result;

    RETURN result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION update_prior_visit_summary_bypass(TEXT, INTEGER, JSONB) TO anon;
GRANT EXECUTE ON FUNCTION update_prior_visit_summary_bypass(TEXT, INTEGER, JSONB) TO authenticated;

-- ============================================================================
-- STEP 3: fast read of the most recent prior_visit_summary for a patient.
-- Used by the UI when opening a returning patient in DataInputSection.
-- Returns the JSONB summary plus the visit metadata so the card can render
-- "Last consultation: 2026-04-12" without an extra round-trip.
-- ============================================================================
DROP FUNCTION IF EXISTS get_latest_prior_visit_summary(TEXT);

CREATE OR REPLACE FUNCTION get_latest_prior_visit_summary(p_patient_nric TEXT)
RETURNS JSON AS $$
DECLARE
    result JSON;
BEGIN
    IF NOT is_valid_nric(p_patient_nric) THEN
        RAISE EXCEPTION 'Invalid NRIC format';
    END IF;

    SELECT json_build_object(
        'consultation_id', id,
        'consultation_number', consultation_number,
        'consultation_time', consultation_time,
        'prior_visit_summary', prior_visit_summary
    )
    INTO result
    FROM consultations
    WHERE patient_nric = p_patient_nric
      AND prior_visit_summary IS NOT NULL
    ORDER BY consultation_time DESC, id DESC
    LIMIT 1;

    RETURN COALESCE(result, json_build_object('prior_visit_summary', NULL));
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION get_latest_prior_visit_summary(TEXT) TO anon;
GRANT EXECUTE ON FUNCTION get_latest_prior_visit_summary(TEXT) TO authenticated;

-- ============================================================================
-- DONE.
--
-- Wiring expected on the client side:
--   1. On consultation save → save_consultation_bypass(...) as before.
--   2. Fire-and-forget POST /clinical/summarise-prior with the saved notes.
--   3. With its response, call update_prior_visit_summary_bypass(nric, n, json).
--   4. On NEXT consultation open → get_latest_prior_visit_summary(nric);
--      pass the JSONB into PatientCase.prior_visit before /clinical/plan/stream.
-- ============================================================================
