import re

file_path = r"c:\Users\jiaqi\OneDrive\Documents\CPG\markdown\Prevention-Diagnosis-Management-of-IE\section-10-appendices.md"

with open(file_path, "r", encoding="utf-8") as f:
    text = f.read()

child_start_marker = "| Drug | Dose for normal renal function | Method | Adjustment for renal failure Estimated GFR (ml/min) > 50-90"
child_end_marker = "| Flucytosine<sup>5,10,27</sup><br>*Infants, children and adolescents* | 150 mg/kg/day PO in 4 equally divided doses | - | Normal dose | GFR 30-50: 25-37.5 mg/kg/dose 8 hourly<br>GFR 10-29: 25-37.5 mg/kg/dose 12 hourly | GFR < 10: 25-37.5 mg/kg/dose daily | HD/PD: 25-37.5 mg/kg/dose daily<br>CRRT: 25-37.5 mg/kg/dose 8 hourly | |\n"

child_table_replacement = """| Drug | Age | Dose for normal renal function | Method | Adjustment for renal failure Estimated GFR (ml/min) > 50-90 | Adjustment for renal failure Estimated GFR (ml/min) 10-50 | Adjustment for renal failure Estimated GFR (ml/min) < 10 | Dose in patients undergoing renal replacement therapies | Comments |
|---|---|---|---|---|---|---|---|---|
| **AMINOGLYCOSIDES** | | | | | | | | |
| **Gentamicin**<sup>5-7</sup> | Infants, children and adolescents | 1 mg/kg IV 8 hourly | D & I | All ages, give first dose as above and await plasma level result before further dosing. If trough level is still high after 36 hours consider reducing dose.<br><br>**Blood levels/TDM:**<br>• Take level 6 hours before 3rd dose (6 hours before 2nd dose if renal function is unstable). Repeat daily until stable then every 3 doses.<br>• Pre-dose (‘trough’) concentration<br>> < 2 µmol/ml (< 1mcg/ml for paediatrics)<br>> < 4 µmol/ml (< 2mcg/ml for NICU/PICU)<br>• Re-dose patient at 24 hours if trough level achieved (at 36 hours if on 36 hour dosing). If trough is high, recheck level 12 hours after that level was taken and re-dose after that if level now in range. Dosing adjustment is to avoid accumulation, but do not delay at the detriment of not treating the patient.<br>• In very overweight or grossly oedematous patients, use lean body weight for calculating dose. | All ages, give first dose as above and await plasma level result before further dosing. If trough level is still high after 36 hours consider reducing dose.<br><br>**Blood levels/TDM:**<br>• Take level 6 hours before 3rd dose (6 hours before 2nd dose if renal function is unstable). Repeat daily until stable then every 3 doses.<br>• Pre-dose (‘trough’) concentration<br>> < 2 µmol/ml (< 1mcg/ml for paediatrics)<br>> < 4 µmol/ml (< 2mcg/ml for NICU/PICU)<br>• Re-dose patient at 24 hours if trough level achieved (at 36 hours if on 36 hour dosing). If trough is high, recheck level 12 hours after that level was taken and re-dose after that if level now in range. Dosing adjustment is to avoid accumulation, but do not delay at the detriment of not treating the patient.<br>• In very overweight or grossly oedematous patients, use lean body weight for calculating dose. | All ages, give first dose as above and await plasma level result before further dosing. If trough level is still high after 36 hours consider reducing dose.<br><br>**Blood levels/TDM:**<br>• Take level 6 hours before 3rd dose (6 hours before 2nd dose if renal function is unstable). Repeat daily until stable then every 3 doses.<br>• Pre-dose (‘trough’) concentration<br>> < 2 µmol/ml (< 1mcg/ml for paediatrics)<br>> < 4 µmol/ml (< 2mcg/ml for NICU/PICU)<br>• Re-dose patient at 24 hours if trough level achieved (at 36 hours if on 36 hour dosing). If trough is high, recheck level 12 hours after that level was taken and re-dose after that if level now in range. Dosing adjustment is to avoid accumulation, but do not delay at the detriment of not treating the patient.<br>• In very overweight or grossly oedematous patients, use lean body weight for calculating dose. | | |
| **CEPHALOSPORINS** | | | | | | | | |
| **Cefazolin**<sup>8-11</sup> | Infants, children and adolescents | 100 mg/kg/**day** IV in 3 equally divided doses | D & I | GFR 40-70:<br>Normal initial dose then 60% of total daily dose given in 2 equal doses | GFR 20-40:<br>Normal initial dose then 25% of total daily dose given in 2 equal doses;<br>GFR 5-20:<br>Normal initial dose then 10% of total daily dose daily | 25 mg/kg IV daily | HD/PD: 25 mg/kg IV daily<br><br>CRRT: 25 mg/kg IV 8 hourly | |
| **Cefepime**<sup>7,12,13</sup> | Infants, children and adolescents | 50 mg/kg IV 8 hourly (Max. single dose 2 g) | D & I | Normal dose | 25-50 mg/kg IV 12 to 18 hourly | 25-50 mg/kg IV daily | HD: LD of 25-50 mg/kg IV on Day 1 then 12.5-25 mg/kg IV daily; dose after HD or give supplemental same dose after HD session<br>PD: Normal dose daily<br>CRRT: Normal dose 12 hourly | |
| **Ceftriaxone**<sup>5-7,10,12,13</sup> | Infants, children and adolescents | 100 mg/kg IV once daily | - | Normal dose | Normal dose | Max 50 mg/kg IV daily (max. 2 g daily) | HD/CAPD: 50 mg/kg IV daily (max. 2 g daily).<br>On HD days scheduled doses should be administered after HD session.<br>CRRT: Normal dose | Ceftriaxone should not be administered to premature, acidotic, jaundiced neonates or those with impaired or reduced bilirubin binding. |
| **PENICILLINS** | | | | | | | | |
| **Ampicillin**<sup>7,10,14,15</sup> | Infants, children and adolescents | 200-300 mg/kg/**day** IV in 4-6 equally divided doses (max. 12 g/**day**) | I | Normal dose | GFR 10-30:<br>Normal dose 6 to 12 hourly | Normal dose 12 hourly | HD: Normal dose 12 hourly; dose after HD or give supplemental same dose after HD session<br>CVVH: Normal LD then normal dose 8 to 12 hourly<br>CVVHD: Normal LD then normal dose 8 hourly<br>CVVHDF: Normal LD then normal dose 6 to 8 hourly | |
| **Ampicillin (AM) + Sulbactam (SB)**<br>**(IV 2:1)**<sup>10,15-17</sup> | Infants, children and adolescents < 40 kg | 200-300 mg AM/kg/**day** IV in 4-6 equally divided doses | I | Normal dose | FR 15-29:<br>Normal dose 12 hourly;<br>GFR 5-14:<br>Normal dose daily | Normal dose daily | Dose expressed as AM component<br>HD: Normal dose 12 to 24 hourly; give after dialysis on dialysis days<br>CVVH: Max dose as LD then normal dose 8 to 12 hourly<br>CVVHD: Max dose as LD then normal dose 8 hourly<br>CVVHDF: Max dose as LD then normal dose 6 to 8 hourly | |
| **Cloxacillin**<sup>18</sup> | Children and adolescents | 200-300 mg/kg/**day** IV in 4-6 equally divided doses (max. 2 g/**dose**) | - | Normal dose | Normal dose | Normal dose | HD: Dosage adjustment not needed | |
| **Benzyl Penicillin**<sup>6,10,19</sup><br>**(Crystalline Penicillin)** | Infants, children and adolescents | 200,000- 300,000 units/kg/**day** IV in 4-6 equally divided doses | I | Normal dose | Normal dose 8 to 12 hourly | Normal dose 12 hourly | HD: Normal dose 8 to 12 hourly; give afer dialysis on dialysis days<br>CAVH/CVVH/CVVHD: Normal dose 8 to 12 hourly | |
| **MISCELLANEOUS** | | | | | | | | |
| **Daptomycin**<sup>10,20</sup> | Children ≥ 2 years and adolescents | 10 mg/kg IV daily | I | Normal dose | GFR 10-29:<br>67% of full dose daily | 67% of full dose 48 hourly | HD/PD: 67% of full dose 48 hourly after dialysis | In paediatric patients, daptomycin is not routinely used as a 1st line therapy. Avoid using in < 12 months due to musculoskeletal, neuromuscular and nervous system adverse effects. |
| **Vancomycin**<sup>6,10,21</sup> | Infants, children and adolescents | 40-60 mg/kg/day IV in 2-3 equally divided doses (Initial dose is based on actual body weight; subsequent dosing based on serum trough levels) | D & I | Doses should be reduced in renal failure according to blood levels<br>• Trough level monitoring:<br>> Only give subsequent doses when vancomycin level reaches trough target<br>> Therapeutic level: Trough 7-10 umol/l (10-15 mg/l) or 10-14 umol/l (15-20 mg/l)<br>> Trough levels should be obtained approximately 30 minutes of the next dose<br>> Approx. time to steady state 1-2 days<br>> Peak levels are not usually required | Doses should be reduced in renal failure according to blood levels<br>• Trough level monitoring:<br>> Only give subsequent doses when vancomycin level reaches trough target<br>> Therapeutic level: Trough 7-10 umol/l (10-15 mg/l) or 10-14 umol/l (15-20 mg/l)<br>> Trough levels should be obtained approximately 30 minutes of the next dose<br>> Approx. time to steady state 1-2 days<br>> Peak levels are not usually required | Doses should be reduced in renal failure according to blood levels<br>• Trough level monitoring:<br>> Only give subsequent doses when vancomycin level reaches trough target<br>> Therapeutic level: Trough 7-10 umol/l (10-15 mg/l) or 10-14 umol/l (15-20 mg/l)<br>> Trough levels should be obtained approximately 30 minutes of the next dose<br>> Approx. time to steady state 1-2 days<br>> Peak levels are not usually required | HD/CAPD: 10 mg/kg IV as needed per serum concentration monitoring<br>CRRT: 10 mg/kg IV 12 to 24 hourly, monitoring serum concentration | |
| **Rifampicin**<sup>10,22,23</sup> | Children and adolescents | 20 mg/kg/day PO in 3 divided doses (max. 900 mg/day) | D | Normal dose | Normal dose | Normal dose | HD/CAPD/CRRT: Normal dose | |
| **ANTIFUNGALS** | | | | | | | | |
| **Amphotericin B deoxycholate**<sup>22,24</sup> | Infants, children and adolescents | After test dose 1 mg/kg IV daily | - | Avoid; use normal dose if only no alternative (see Comments). If renal dysfunction is due to drug, the total daily dose can be decreased by 50% or the dose can be given every other day | Avoid; use normal dose if only no alternative (see Comments). If renal dysfunction is due to drug, the total daily dose can be decreased by 50% or the dose can be given every other day | Avoid; use normal dose if only no alternative (see Comments). If renal dysfunction is due to drug, the total daily dose can be decreased by 50% or the dose can be given every other day | HD/PD/CRRT: If essential use normal dose | Amphotericin is nephrotoxic; monitor serum creatinine closely; lipid formulations are less nephrotoxic. |
| **Amphotericin B lipid complex**<sup>22,25</sup> | Infants, children and adolescents | 3-5 mg/kg IV daily | - | No dosage adjustment required in pre existing renal failure. | No dosage adjustment required in pre existing renal failure. | No dosage adjustment required in pre existing renal failure. | HD/PD/CRRT: Normal dose; consider standard amphotericin due to cost | Amphotericin is highly nephrotoxic; monitor serum creatinine closely. |
| **Fluconazole**<sup>6,7,10,22,26</sup> | Infants, children and adolescents | 6-12 mg/kg PO/IV daily | D | Normal dose | Normal LD then 50% of normal dose daily | Normal LD then 50% of normal dose 48 hourly | HD: 100% of normal dose 3x/week after HD session or 50% of normal dose every 48 hours; administer after dialysis on dialysis days<br>PD: 50% of normal dose 48 hourly<br>CRRT: 6 mg/kg/dose daily | Refer to product information for more dosing details. |
| **Flucytosine**<sup>5,10,27</sup> | Infants, children and adolescents | 150 mg/kg/day PO in 4 equally divided doses | - | Normal dose | GFR 30-50:<br>25-37.5 mg/kg/dose 8 hourly<br>GFR 10-29:<br>25-37.5 mg/kg/dose 12 hourly | GFR < 10:<br>25-37.5 mg/kg/dose daily | HD/PD: 25-37.5 mg/kg/dose daily<br>CRRT: 25-37.5 mg/kg/dose 8 hourly | |
"""

import sys

child_start_idx = text.find(child_start_marker)
child_end_idx = text.find(child_end_marker) + len(child_end_marker)

if child_start_idx != -1 and text.find(child_end_marker) != -1:
    text = text[:child_start_idx] + child_table_replacement + text[child_end_idx:]
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(text)
    print("Successfully replaced child table!")
else:
    print(f"Could not find boundaries: start={child_start_idx}, end={text.find(child_end_marker)}")
    sys.exit(1)
