import React from 'react';
import {
  X,
  User,
  FileText,
  FileSpreadsheet,
  BarChart2
} from 'lucide-react';
import { useTheme } from '../../context/ThemeContext';
import { expandBulletMeds } from '../../lib/helpers';

const PatientQuickView = ({ patient, triage, isOpen, onClose, onExportPDF, onExportCSV, onViewChart }) => {
  const { isDark, accent } = useTheme();

  if (!isOpen || !patient) return null;

  const handleExportPDF = () => {
    const vitalsHistory = patient.vitalsHistory || [];
    let vitalsHistoryText = '';
    if (vitalsHistory.length > 0) {
      vitalsHistoryText = `\n\nVITALS HISTORY (Last ${vitalsHistory.length} readings)\n----------------------------------------`;
      vitalsHistory.forEach(v => {
        const item = typeof v === 'string' ? JSON.parse(v) : v;
        vitalsHistoryText += `\n${item.date}: BP ${item.bpSystolic}/${item.bpDiastolic} | HR ${item.hr} | SpO2 ${item.spo2}% | Weight ${item.weight}kg`;
      });
    }
    const content = `
PATIENT SUMMARY REPORT
======================
Generated: ${new Date().toLocaleDateString('en-MY', { dateStyle: 'full' })}

PATIENT INFORMATION
-------------------
Name: ${patient.name}
Age: ${patient.age} years old
Gender: ${patient.gender}
NRIC: ${patient.nsn}

VITAL SIGNS
-----------
Blood Pressure: ${triage?.vitals?.bp || 'N/A'}
Heart Rate: ${triage?.vitals?.hr || 'N/A'} bpm
SpO2: ${triage?.vitals?.spo2 || 'N/A'}%
Temperature: ${triage?.vitals?.temp || 'N/A'}°C
Respiratory Rate: ${triage?.vitals?.rr || 'N/A'} /min

CHIEF COMPLAINT
---------------
${triage?.chiefComplaint || 'N/A'}
${vitalsHistoryText}

---
Report generated by CPG LLM - Connecting Values in Healthcare
    `.trim();
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `patient_${patient.nsn}_summary.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    if (onExportPDF) onExportPDF();
  };

  const handleExportCSV = () => {
    const headers = ['Field', 'Value'];
    const rows = [
      ['Name', patient.name],
      ['Age', patient.age],
      ['Gender', patient.gender],
      ['NRIC', patient.nsn],
      ['Blood Pressure', triage?.vitals?.bp || 'N/A'],
      ['Heart Rate', `${triage?.vitals?.hr || 'N/A'} bpm`],
      ['SpO2', `${triage?.vitals?.spo2 || 'N/A'}%`],
      ['Temperature', `${triage?.vitals?.temp || 'N/A'}°C`],
      ['Chief Complaint', triage?.chiefComplaint || 'N/A'],
      ['Export Date', new Date().toISOString()]
    ];
    const csvContent = [headers.join(','), ...rows.map(row => row.map(cell => `"${cell}"`).join(','))].join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `patient_${patient.nsn}_data.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    if (onExportCSV) onExportCSV();
  };

  const getBPColor = (status) => {
    const colors = { normal: 'text-emerald-500', high: 'text-amber-500', critical: 'text-red-600 font-bold' };
    return colors[status] || (isDark ? 'text-white' : 'text-slate-800');
  };

  const getInitials = (name) => {
    if (!name) return 'P';
    const parts = name.split(' ');
    return parts.length >= 2
      ? (parts[0][0] + parts[parts.length - 1][0]).toUpperCase()
      : name.substring(0, 2).toUpperCase();
  };

  const meds = expandBulletMeds(patient.currentMeds);

  return (
    <>
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-black/50 backdrop-blur-sm z-[60] transition-opacity"
        onClick={onClose}
      />

      {/* Modal */}
      <div className={`fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 z-[70]
        w-full max-w-lg max-h-[90vh] overflow-auto rounded-2xl shadow-2xl
        ${isDark ? 'bg-slate-900 border border-white/10' : 'bg-white border border-slate-200'}`}
      >
        {/* Header */}
        <div className={`sticky top-0 flex items-center justify-between px-5 py-4 border-b z-10
          ${isDark ? 'bg-slate-900 border-white/10' : 'bg-white border-slate-200'}`}>
          <h2 className={`text-base font-semibold flex items-center gap-2 ${isDark ? 'text-white' : 'text-slate-800'}`}>
            <User className={`w-4 h-4 ${accent.text}`} strokeWidth={1.5} />
            Patient Quick View
          </h2>
          <button
            onClick={onClose}
            className={`p-1.5 rounded-lg transition-colors
              ${isDark ? 'hover:bg-white/10 text-slate-400 hover:text-white' : 'hover:bg-slate-100 text-slate-500 hover:text-slate-800'}`}
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        <div className="p-5 space-y-5">

          {/* Identity Banner — mirrors MyPatients row */}
          <div className={`flex items-center gap-4 p-4 rounded-xl ${isDark ? 'bg-white/5 border border-white/10' : 'bg-slate-50 border border-slate-200'}`}>
            <div className={`w-12 h-12 rounded-full flex items-center justify-center text-lg font-bold flex-shrink-0
              bg-gradient-to-br ${accent.gradient} text-white`}>
              {getInitials(patient.name)}
            </div>
            <div className="min-w-0 flex-1">
              <p className={`font-semibold text-base truncate ${isDark ? 'text-white' : 'text-slate-800'}`}>{patient.name}</p>
              <p className={`text-xs mt-0.5 ds-numeric ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>
                {patient.age} y/o · {patient.gender}
                {patient.nsn && <span className="ds-mono ml-2 opacity-70">· {patient.nsn}</span>}
              </p>
            </div>
          </div>

          {/* Demographics data grid — same pattern as MyPatients detail panel */}
          <div className={`grid grid-cols-2 text-sm divide-y md:divide-y-0 md:grid-cols-4 md:divide-x
            ${isDark ? 'divide-white/10' : 'divide-slate-200'}
            border rounded-xl overflow-hidden ${isDark ? 'border-white/10' : 'border-slate-200'}`}>
            {[
              { label: 'Age', value: patient.age ? `${patient.age} yrs` : '—', cls: 'ds-numeric' },
              { label: 'Gender', value: patient.gender || '—', cls: '' },
              { label: 'Race', value: patient.race || '—', cls: '' },
              { label: 'Allergies', value: patient.allergies
                  ? (Array.isArray(patient.allergies) ? patient.allergies.join(', ') : String(patient.allergies))
                  : 'None', cls: patient.allergies ? 'text-red-500' : '' },
            ].map(({ label, value, cls }) => (
              <div key={label} className={`px-3 py-2.5 ${isDark ? 'bg-white/3' : 'bg-white'}`}>
                <p className="ds-eyebrow mb-1">{label}</p>
                <p className={`font-medium text-sm ${cls} ${!cls.includes('text-') ? (isDark ? 'text-white' : 'text-slate-800') : ''}`}>{value}</p>
              </div>
            ))}
          </div>

          {/* Chief Complaint — accent left border panel */}
          {triage?.chiefComplaint && (
            <div className={`p-4 rounded-xl border-l-2 border-[var(--accent-primary)]
              ${isDark ? 'bg-[var(--accent-primary)]/5 border border-[var(--accent-primary)]/20'
                       : 'bg-[var(--accent-primary)]/5 border border-[var(--accent-primary)]/20'}`}>
              <p className="ds-eyebrow mb-2">Chief Complaint</p>
              <p className={`text-sm ${isDark ? 'text-white' : 'text-slate-800'}`}>{triage.chiefComplaint}</p>
            </div>
          )}

          {/* Vital Signs — blue left border panel */}
          {triage?.vitals && (
            <div className={`p-4 rounded-xl border-l-2 border-blue-400
              ${isDark ? 'bg-blue-500/5 border border-blue-500/20' : 'bg-blue-50/60 border border-blue-200'}`}>
              <p className="ds-eyebrow mb-3" style={{ color: 'rgb(59,130,246)' }}>Vital Signs</p>
              <div className="grid grid-cols-2 gap-2">
                {[
                  { label: 'Blood Pressure', value: `${triage.vitals.bp} mmHg`, color: getBPColor(triage.vitals.bpStatus) },
                  { label: 'Heart Rate', value: `${triage.vitals.hr} bpm`, color: isDark ? 'text-white' : 'text-slate-800' },
                  { label: 'SpO₂', value: `${triage.vitals.spo2}%`, color: isDark ? 'text-white' : 'text-slate-800' },
                  { label: 'Temperature', value: `${triage.vitals.temp}°C`, color: isDark ? 'text-white' : 'text-slate-800' },
                ].map(({ label, value, color }) => (
                  <div key={label} className={`px-3 py-2 rounded-lg ${isDark ? 'bg-white/5' : 'bg-white/70'}`}>
                    <p className={`text-[10px] font-medium uppercase tracking-wider ${isDark ? 'text-slate-500' : 'text-slate-400'}`}>{label}</p>
                    <p className={`text-sm font-semibold ds-numeric mt-0.5 ${color}`}>{value}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Current Medications — amber left border panel */}
          {meds.length > 0 && (
            <div className={`p-4 rounded-xl border-l-2 border-amber-400
              ${isDark ? 'bg-amber-500/5 border border-amber-500/20' : 'bg-amber-50/60 border border-amber-200'}`}>
              <p className="ds-eyebrow mb-2" style={{ color: 'rgb(245,158,11)' }}>Current Medications</p>
              <div className="space-y-1">
                {meds.map((med, idx) => (
                  <p key={idx} className={`text-sm ${isDark ? 'text-white' : 'text-slate-800'}`}>
                    · {typeof med === 'object'
                      ? `${med.name || med.medication || 'Unknown'} ${med.dose || ''} ${med.frequency || ''}`.trim()
                      : String(med)}
                  </p>
                ))}
              </div>
            </div>
          )}

          {/* Action row */}
          <div className={`pt-4 border-t ${isDark ? 'border-white/10' : 'border-slate-200'} flex flex-col gap-2`}>
            <div className="flex gap-2">
              <button
                onClick={handleExportPDF}
                className={`flex-1 flex items-center justify-center gap-2 px-4 py-2.5 rounded-lg font-medium text-sm transition-all
                  bg-gradient-to-r ${accent.gradient} text-white shadow-md ${accent.shadow} hover:opacity-90`}
              >
                <FileText className="w-4 h-4" strokeWidth={1.5} />
                Export PDF
              </button>
              <button
                onClick={handleExportCSV}
                className={`flex-1 flex items-center justify-center gap-2 px-4 py-2.5 rounded-lg font-medium text-sm transition-all
                  ${isDark ? 'bg-white/8 hover:bg-white/16 text-white border border-white/10' : 'bg-slate-100 hover:bg-slate-200 text-slate-700 border border-slate-200'}`}
              >
                <FileSpreadsheet className="w-4 h-4" strokeWidth={1.5} />
                Export CSV
              </button>
            </div>
            {onViewChart && (
              <button
                onClick={() => { onClose(); onViewChart(patient); }}
                className={`w-full flex items-center justify-center gap-2 px-4 py-2.5 rounded-lg font-medium text-sm transition-all
                  ${isDark ? 'bg-emerald-500/15 hover:bg-emerald-500/25 text-emerald-400 border border-emerald-500/25'
                           : 'bg-emerald-50 hover:bg-emerald-100 text-emerald-700 border border-emerald-200'}`}
              >
                <BarChart2 className="w-4 h-4" strokeWidth={1.5} />
                View Vital Signs Chart
              </button>
            )}
          </div>

        </div>
      </div>
    </>
  );
};

export default PatientQuickView;
